<?php require_once("../util.php"); ?>
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8"/>
        <title>Servicios</title>
        <link href='//fonts.googleapis.com/css?family=Lato:300' rel='stylesheet' type='text/css'>
    </head>
    <body>
        <?php if (isset($idZombie)) : ?>
            <?php echo getDescripcionZombieById($idZombie); ?>
        <?php else: ?>
            <?php echo getDescripcionZombie(); ?>
        <?php endif; ?>
    </body>
</html>